services:
  postgres:
    image: postgres:16-alpine
    container_name: test-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root_secret}
      POSTGRES_DB: ${DB_NAME:-test_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-root} -d ${DB_NAME:-test_db}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: test-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root_secret}
      DB_NAME: ${DB_NAME:-test_db}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
      WOMPI_API_URL: ${WOMPI_API_URL:-https://api-sandbox.co.uat.wompi.dev/v1}
      WOMPI_PUBLIC_KEY: ${WOMPI_PUBLIC_KEY:-pub_stagtest_g2u0HQd3ZMh05hsSgTS2lUV8t3s4mOt7}
      WOMPI_PRIVATE_KEY: ${WOMPI_PRIVATE_KEY:-prv_stagtest_5i0ZGIGiFcDQifYsXxvsny7Y37tKqFWg}
      WOMPI_EVENTS_KEY: ${WOMPI_EVENTS_KEY:-stagtest_events_2PDUmhMywUkvb1LvxYnayFbmofT7w39N}
      WOMPI_INTEGRITY_KEY: ${WOMPI_INTEGRITY_KEY:-stagtest_integrity_nAIBuqayW70XpUqJS4qf4STYiISd89Fp}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  backend_node_modules:
